import type { CaptureBundle } from '@shared/types';
import type { TriageFields } from '@shared/messaging';

// Shared issue-body formatting reused by every integration so a filed bug looks
// the same in Linear, Jira, or GitHub. Markdown — GitHub/Linear render it
// natively; Jira maps it to ADF (see jira.ts).

// Output caps. Slack rejects oversized text outright (msg_too_long fails the
// whole filing) and GitHub caps issue bodies at 65,536 chars — so a runaway
// console error or giant generated test must never produce an unbounded body.
const MAX_CONSOLE_MSG = 500;
const MAX_TOTAL = 60_000;
const TRUNCATION_MARKER = '… [truncated]';

function fmtSteps(bundle: CaptureBundle): string {
  if (bundle.steps.length === 0) return '_No steps recorded._';
  return bundle.steps
    .map((s, i) => {
      const detail = s.selector ? ` \`${s.selector}\`` : '';
      const value = s.value ? ` → "${s.value}"` : '';
      return `${i + 1}. **${s.kind}** ${s.label}${detail}${value}`;
    })
    .join('\n');
}

function fmtNetwork(bundle: CaptureBundle): string {
  const failed = bundle.network.filter((n) => n.failed);
  if (failed.length === 0) return '_No failed requests._';
  return failed
    .map((n) => `- \`${n.status || 'ERR'}\` ${n.method} ${n.url} (${n.durationMs}ms)`)
    .join('\n');
}

function fmtConsole(bundle: CaptureBundle): string {
  const errors = bundle.console.filter((c) => c.level === 'error');
  if (errors.length === 0) return '_No console errors._';
  return errors
    .map((c) => {
      // Cap each message — minified-stack errors can be hundreds of KB each.
      const msg =
        c.message.length > MAX_CONSOLE_MSG
          ? `${c.message.slice(0, MAX_CONSOLE_MSG)}${TRUNCATION_MARKER}`
          : c.message;
      return `- \`${msg}\``;
    })
    .join('\n');
}

// Triage (team/assignee/priority) is rendered as body TEXT, not mapped to
// tracker-native fields: native priority/assignee values that don't exist in
// the target project/tracker cause 400s and kill the whole filing, whereas a
// body line always lands.
function fmtTriage(fields: TriageFields | undefined): string | null {
  if (!fields) return null;
  const parts = [
    fields.team ? `team ${fields.team}` : null,
    fields.assignee ? `assignee ${fields.assignee}` : null,
    fields.priority ? `priority ${fields.priority}` : null,
  ].filter((p): p is string => p !== null);
  return parts.length > 0 ? `**Triage:** ${parts.join(' · ')}` : null;
}

export interface DescribeOpts {
  fields?: TriageFields | undefined;
}

export function describeBundle(bundle: CaptureBundle, opts?: DescribeOpts): string {
  const env = bundle.environment;
  const sections = [
    '## Reproduction steps',
    fmtSteps(bundle),
    '',
    '## Failed requests',
    fmtNetwork(bundle),
    '',
    '## Console errors',
    fmtConsole(bundle),
    '',
    '## Environment',
    `- ${env.browser} · ${env.os}`,
    `- Viewport ${env.viewport.width}×${env.viewport.height} · DPR ${env.dpr}`,
    `- ${env.locale} · ${env.url}`,
  ];
  const triage = fmtTriage(opts?.fields);
  if (triage) {
    sections.push('', '## Triage', triage);
  }
  if (bundle.aiAnalysis) {
    const a = bundle.aiAnalysis;
    sections.push(
      '',
      `## AI triage (${a.provider} · ${a.model})`,
      a.summary,
      '',
      '**Likely root causes**',
      ...a.rootCauses.map((c) => `- ${c}`),
      '',
      '**Suggested debugging steps**',
      ...a.debuggingSteps.map((s, i) => `${i + 1}. ${s}`),
    );
  }
  if (bundle.generatedTest) {
    sections.push(
      '',
      '## Regression test (generated by Gotcha)',
      '```ts',
      bundle.generatedTest.source.trim(),
      '```',
    );
  }
  sections.push('', `— filed by Gotcha · redaction ${bundle.redacted ? 'on' : 'off'}`);
  const text = sections.join('\n');
  // Total budget: the generated-test embed is kept but trimmed along with
  // everything else past the cap, so the body always fits every tracker.
  return text.length > MAX_TOTAL
    ? `${text.slice(0, MAX_TOTAL)}\n${TRUNCATION_MARKER}`
    : text;
}
