import type { CaptureBundle } from '@shared/types';

// Shared issue-body formatting reused by every integration so a filed bug looks
// the same in Linear, Jira, or GitHub. Markdown — GitHub/Linear render it
// natively; Jira's wiki renderer accepts a close-enough subset.
function fmtSteps(bundle: CaptureBundle): string {
  if (bundle.steps.length === 0) return '_No steps recorded._';
  return bundle.steps
    .map((s, i) => {
      const detail = s.selector ? ` \`${s.selector}\`` : '';
      const value = s.value ? ` → "${s.value}"` : '';
      return `${i + 1}. **${s.kind}** ${s.label}${detail}${value}`;
    })
    .join('\n');
}

function fmtNetwork(bundle: CaptureBundle): string {
  const failed = bundle.network.filter((n) => n.failed);
  if (failed.length === 0) return '_No failed requests._';
  return failed
    .map((n) => `- \`${n.status || 'ERR'}\` ${n.method} ${n.url} (${n.durationMs}ms)`)
    .join('\n');
}

function fmtConsole(bundle: CaptureBundle): string {
  const errors = bundle.console.filter((c) => c.level === 'error');
  if (errors.length === 0) return '_No console errors._';
  return errors.map((c) => `- \`${c.message}\``).join('\n');
}

export function describeBundle(bundle: CaptureBundle): string {
  const env = bundle.environment;
  const sections = [
    '## Reproduction steps',
    fmtSteps(bundle),
    '',
    '## Failed requests',
    fmtNetwork(bundle),
    '',
    '## Console errors',
    fmtConsole(bundle),
    '',
    '## Environment',
    `- ${env.browser} · ${env.os}`,
    `- Viewport ${env.viewport.width}×${env.viewport.height} · DPR ${env.dpr}`,
    `- ${env.locale} · ${env.url}`,
  ];
  if (bundle.aiAnalysis) {
    const a = bundle.aiAnalysis;
    sections.push(
      '',
      `## AI triage (${a.provider} · ${a.model})`,
      a.summary,
      '',
      '**Likely root causes**',
      ...a.rootCauses.map((c) => `- ${c}`),
      '',
      '**Suggested debugging steps**',
      ...a.debuggingSteps.map((s, i) => `${i + 1}. ${s}`),
    );
  }
  if (bundle.generatedTest) {
    sections.push(
      '',
      '## Regression test (generated by Gotcha)',
      '```ts',
      bundle.generatedTest.source.trim(),
      '```',
    );
  }
  sections.push('', `— filed by Gotcha · redaction ${bundle.redacted ? 'on' : 'off'}`);
  return sections.join('\n');
}
