import { describe, it, expect, beforeEach } from 'vitest';
import { storageLocal, mockFetch } from '../setup/chrome-mock';
import { makeBundle } from '../setup/factory';
import { describeBundle } from '../../src/integrations/format';
import { simulatedRef } from '../../src/integrations/types';
import { getIntegration, INTEGRATIONS } from '../../src/integrations';

describe('integrations — describeBundle (format)', () => {
  it('shows empty-state placeholders when nothing was captured', () => {
    const md = describeBundle(makeBundle());
    expect(md).toContain('_No steps recorded._');
    expect(md).toContain('_No failed requests._');
    expect(md).toContain('_No console errors._');
    expect(md).toContain('redaction off');
  });

  it('renders steps, failed requests, console errors, AI triage and generated test', () => {
    const md = describeBundle(
      makeBundle({
        redacted: true,
        steps: [{ id: 's1', kind: 'click', selector: '#go', label: 'Go', value: 'x', ts: 1 }],
        network: [
          { id: 'n1', url: 'https://a/x', method: 'GET', status: 500, durationMs: 12, failed: true, ts: 1 },
          { id: 'n2', url: 'https://a/y', method: 'GET', status: 200, durationMs: 5, failed: false, ts: 2 },
        ],
        console: [
          { id: 'c1', level: 'error', message: 'boom', ts: 1 },
          { id: 'c2', level: 'log', message: 'noise', ts: 2 },
        ],
        aiAnalysis: {
          summary: 'It broke',
          rootCauses: ['cause a'],
          debuggingSteps: ['step 1'],
          suggestedTitle: 't',
          severity: { level: 'P1', reason: 'r' },
          provider: 'openai',
          model: 'gpt-4.1-mini',
          at: 1,
        },
        generatedTest: { filename: 'g.spec.ts', source: 'import x;' },
      }),
    );
    expect(md).toContain('1. **click** Go `#go` → "x"');
    expect(md).toContain('`500` GET https://a/x (12ms)');
    expect(md).toContain('`boom`');
    expect(md).not.toContain('noise'); // non-error console line excluded
    expect(md).toContain('## AI triage (openai · gpt-4.1-mini)');
    expect(md).toContain('cause a');
    expect(md).toContain('## Regression test (generated by Gotcha)');
    expect(md).toContain('redaction on');
  });
});

describe('integrations — simulatedRef', () => {
  it('uses the right prefix per integration', () => {
    expect(simulatedRef('linear').identifier).toMatch(/^GOT-\d{3}$/);
    expect(simulatedRef('jira').identifier).toMatch(/^BUG-\d{3}$/);
    expect(simulatedRef('github').identifier).toMatch(/^#\d{3}$/);
    expect(simulatedRef('slack').identifier).toMatch(/^MSG-\d{3}$/);
    expect(simulatedRef('linear').simulated).toBe(true);
  });
});

describe('integrations — registry', () => {
  it('resolves all four integrations by id', () => {
    for (const id of ['linear', 'jira', 'github', 'slack'] as const) {
      expect(getIntegration(id).id).toBe(id);
    }
    expect(INTEGRATIONS).toHaveLength(4);
  });
});

describe('integrations — simulate without credentials', () => {
  it('every integration returns a simulated ref when unconfigured', async () => {
    for (const id of ['linear', 'jira', 'github', 'slack'] as const) {
      const r = await getIntegration(id).file(makeBundle());
      expect(r.simulated).toBe(true);
    }
  });

  it('every integration test() reports not-configured', async () => {
    for (const id of ['linear', 'jira', 'github', 'slack'] as const) {
      expect((await getIntegration(id).test()).ok).toBe(false);
    }
  });
});

describe('integrations — Linear (configured)', () => {
  beforeEach(() => {
    storageLocal.set({ linearApiKey: 'key', linearTeamId: 'team' });
  });

  it('files via GraphQL and returns the created issue', async () => {
    mockFetch(() => ({ body: { data: { issueCreate: { success: true, issue: { identifier: 'GOT-9', url: 'https://l/9' } } } } }));
    const r = await getIntegration('linear').file(makeBundle());
    expect(r).toMatchObject({ integration: 'linear', identifier: 'GOT-9', url: 'https://l/9', simulated: false });
  });

  it('throws the GraphQL error message on failure', async () => {
    mockFetch(() => ({ body: { errors: [{ message: 'bad team' }] } }));
    await expect(getIntegration('linear').file(makeBundle())).rejects.toThrow('bad team');
  });

  it('throws on non-200', async () => {
    mockFetch(() => ({ status: 401, body: {} }));
    await expect(getIntegration('linear').file(makeBundle())).rejects.toThrow('Linear API 401');
  });

  it('test() validates the viewer', async () => {
    mockFetch(() => ({ body: { data: { viewer: { id: 'u1' } } } }));
    expect(await getIntegration('linear').test()).toEqual({ ok: true });
  });
});

describe('integrations — Jira (configured)', () => {
  beforeEach(() => {
    storageLocal.set({ jiraHost: 'x.atlassian.net', jiraEmail: 'e@x.com', jiraToken: 't', jiraProjectKey: 'PROJ' });
  });

  it('files and returns the issue key + browse url', async () => {
    let sentAuth = '';
    mockFetch((_url, init) => {
      sentAuth = String((init?.headers as Record<string, string>)?.Authorization ?? '');
      return { body: { key: 'PROJ-7' } };
    });
    const r = await getIntegration('jira').file(makeBundle());
    expect(r).toMatchObject({ integration: 'jira', identifier: 'PROJ-7', url: 'https://x.atlassian.net/browse/PROJ-7' });
    expect(sentAuth).toMatch(/^Basic /);
  });

  it('throws on API error', async () => {
    mockFetch(() => ({ status: 400, body: {} }));
    await expect(getIntegration('jira').file(makeBundle())).rejects.toThrow('Jira API 400');
  });
});

describe('integrations — GitHub (configured)', () => {
  beforeEach(() => {
    storageLocal.set({ githubToken: 'pat', githubRepo: 'me/repo' });
  });

  it('files an issue and returns the number + url', async () => {
    mockFetch((url) => {
      expect(url).toContain('/repos/me/repo/issues');
      return { body: { number: 42, html_url: 'https://gh/42' } };
    });
    const r = await getIntegration('github').file(makeBundle());
    expect(r).toMatchObject({ identifier: '#42', url: 'https://gh/42', simulated: false });
  });

  it('test() pings the repo', async () => {
    mockFetch(() => ({ ok: true, body: {} }));
    expect(await getIntegration('github').test()).toEqual({ ok: true });
  });
});

describe('integrations — Slack (configured)', () => {
  beforeEach(() => {
    storageLocal.set({ slackWebhookUrl: 'https://hooks.slack.com/x' });
  });

  it('posts Block Kit payload and returns the sentinel identifier', async () => {
    let payload: unknown;
    mockFetch((_url, init) => {
      payload = JSON.parse(String(init?.body));
      return { ok: true, text: 'ok' };
    });
    const r = await getIntegration('slack').file(makeBundle({ title: 'Crash on save' }));
    expect(r).toMatchObject({ integration: 'slack', identifier: 'posted', simulated: false });
    expect(JSON.stringify(payload)).toContain('Crash on save');
  });

  it('throws when the webhook rejects', async () => {
    mockFetch(() => ({ status: 404, body: '' }));
    await expect(getIntegration('slack').file(makeBundle())).rejects.toThrow('Slack webhook 404');
  });

  it('test() posts a probe message', async () => {
    mockFetch(() => ({ ok: true, text: 'ok' }));
    expect(await getIntegration('slack').test()).toEqual({ ok: true });
  });
});
